### ISSUE TITLE
小光!

### ISSUE THREAD

**Issue by xieyuheng** [MiniLight/DNSWhitelist#1]
我回廣州了
不知道你們公司還招人嗎?
我去看看 如果可以的話 可以去實習

**Comment by xieyuheng** [comment]
不好意思了
在這裏打擾你
因爲沒有你別的聯繫方式

**Comment by MiniLight** [comment]
我们现在有在筹备一个新公司，因为投资人的钱还没到位所以还没正式开始招人，只要你不介意稍微等几天就OK

等合伙人从北京回来我们可以见面一起聊聊，大约是在下周吧

**Comment by xieyuheng** [comment]
好的!
不知道是做什麼的公司?
我的郵箱是 xyheme@gmail.com
你可以直接給我發郵件
